Document: acestream
Title: Debian acestream Manual
Author: <insert document author here>
Abstract: This manual describes what acestream is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/acestream/acestream.sgml.gz

Format: postscript
Files: /usr/share/doc/acestream/acestream.ps.gz

Format: text
Files: /usr/share/doc/acestream/acestream.text.gz

Format: HTML
Index: /usr/share/doc/acestream/html/index.html
Files: /usr/share/doc/acestream/html/*.html
